name: Format

on: [push, pull_request]

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: './dogm/'
        exclude: './dogm/cmake'
        extensions: 'h,cpp'
        clangFormatVersion: 9
