name: Build and test on Ubuntu 18.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-ubuntu:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Update package lists
      run: sudo apt update
    - name: Install OpenGL dependencies
      run: sudo apt install libglfw3-dev libglew-dev libglm-dev
    - name: Install OpenCV
      run: sudo apt install libopencv-dev
    - name: Install CUDA toolkit
      run: sudo apt install nvidia-cuda-toolkit
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  ..
      working-directory: dogm
    - name: Build
      run: cmake --build build
      working-directory: dogm
    - name: Test Utils
      run: ctest
      working-directory: dogm/build/demo
    - name: Install clang-tidy
      run: sudo apt install clang-tidy
    - name: Clang-Tidy on cpp (non-failing)
      run: find -iname '*.cpp' | xargs -I{} clang-tidy -p dogm/build | grep -v "clang-diagnostic-error"
    - name: Clang-Tidy on cuda (non-failing)
      run: find dogm/src -iname '*.cu' | xargs -I{} clang-tidy -p build {} -- --cuda-host-only -Idogm/include | grep -v "clang-diagnostic-error"
