name: Unit tests

on: [push, pull_request]

jobs:
  unit-tests-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update package lists
      run: sudo apt update
    - name: Install OpenGL dependencies
      run: sudo apt install libglfw3-dev libglew-dev libglm-dev
    - name: Install OpenCV
      run: sudo apt install libopencv-dev
    - name: Install CUDA toolkit
      run: sudo apt install nvidia-cuda-toolkit
    - name: Configure
      run: mkdir build && cd build && cmake -DBUILD_TESTS=on ..
      working-directory: dogm
    - name: Build
      run: cmake --build build --target utils_spec
      working-directory: dogm
    - name: Test
      run: ./demo/utils/test/utils_spec
      working-directory: dogm/build
